# Generated by Django 3.0.7 on 2020-06-23 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[(1, 'tir'), (2, 'van'), (3, 'minivan')], default='tir', max_length=24)),
                ('volume', models.FloatField()),
                ('max_capacity', models.FloatField()),
                ('max_length', models.FloatField()),
                ('description', models.TextField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.DateTimeField()),
                ('arrival', models.DateTimeField()),
                ('destination', models.CharField(max_length=64)),
                ('place_of_departure', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='przewoz.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(1, 'europaleta'), (2, 'paleta'), (3, 'dłużyca')], max_length=64)),
                ('dimensions', models.CharField(default='120, 80, 14.4', max_length=64)),
                ('description', models.TextField()),
                ('assigned_transit', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='przewoz.Transit')),
                ('assigned_vehicle', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='przewoz.Vehicle')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
