# Generated by Django 3.0.7 on 2020-06-29 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('przewoz', '0002_auto_20200625_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='type',
            field=models.CharField(choices=[('europaleta', 'europaleta'), ('paleta', 'paleta'), ('dłużyca', 'dłużyca')], max_length=64),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('tir', 'tir'), ('van', 'van'), ('minivan', 'minivan')], default='tir', max_length=24),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='przewoz.Cargo')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='przewoz.Transit')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='przewoz.Vehicle')),
            ],
        ),
    ]
