# Generated by Django 3.0.7 on 2020-07-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('przewoz', '0003_auto_20200629_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='remaining_capacity',
            field=models.FloatField(default=0),
        ),
    ]
