# Generated by Django 3.0.7 on 2020-07-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('przewoz', '0004_vehicle_remaining_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
