# Generated by Django 3.0.7 on 2020-07-03 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('przewoz', '0005_cargo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='assigned_transit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='przewoz.Transit'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='przewoz.Vehicle'),
        ),
    ]
